package mcp

import (
	"crypto/hmac"
	"crypto/rand"
	"crypto/sha256"
	"crypto/subtle"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"strings"
	"time"

	"github.com/oklog/ulid/v2"
)

// Token format constants. The header is fixed to HS256 + a key ID; the
// payload is the Claims JSON; the signature is HMAC-SHA256 over
// base64url(header) + "." + base64url(payload). The full string is
// base64url(header) + "." + base64url(payload) + "." + base64url(sig).
//
// Pinning alg=HS256 on the verify side closes the JWT "algorithm
// confusion" footgun (alg=none, alg=HS256-but-key-from-public-RSA, etc.)
// — the verifier ignores whatever the header claims and always uses
// HS256 + the key matched by kid.
const (
	tokenAlg     = "HS256"
	tokenIssuer  = "auto-bot"
	tokenAudMCP  = "mcp"
	maxClockSkew = 60 * time.Second
)

// Claims is the payload of an MCP token. Field names follow JWT
// convention so the wire shape is familiar; the issuer is always
// "auto-bot" and the audience is always "mcp" for tokens this package
// emits or accepts.
type Claims struct {
	Issuer    string   `json:"iss"`
	Audience  string   `json:"aud"`
	Subject   string   `json:"sub"`
	TenantID  string   `json:"tenant_id"`
	Scopes    []string `json:"scopes"`
	IssuedAt  int64    `json:"iat"`
	ExpiresAt int64    `json:"exp"`
	JTI       string   `json:"jti"`
}

// HasScope returns true if the claims grant the supplied scope. Scopes
// are compared verbatim — no wildcard expansion. admin:issue is treated
// as exactly "admin:issue" and does not satisfy any other scope.
func (c Claims) HasScope(required string) bool {
	for _, s := range c.Scopes {
		if s == required {
			return true
		}
	}
	return false
}

// SigningKey is one (kid, key bytes) pair from MCP_SIGNING_KEYS. The
// first key in the parsed slice is the active signer; the rest are
// accepted for verification only (rotation grace).
type SigningKey struct {
	KeyID string
	Key   []byte
}

// ParseSigningKeys parses the MCP_SIGNING_KEYS env-style string.
// Format: "kid1:base64key1,kid2:base64key2[,...]" — comma-separated,
// colon-separated kid/key pairs, key bytes base64-encoded (std or url).
// The first pair is the active signer; the rest are verifier-only.
// Empty key bytes or duplicate kids return an error so misconfiguration
// fails loud at boot.
func ParseSigningKeys(raw string) ([]SigningKey, error) {
	raw = strings.TrimSpace(raw)
	if raw == "" {
		return nil, errors.New("MCP_SIGNING_KEYS is empty")
	}
	parts := strings.Split(raw, ",")
	keys := make([]SigningKey, 0, len(parts))
	seen := map[string]bool{}
	for i, part := range parts {
		part = strings.TrimSpace(part)
		if part == "" {
			continue
		}
		colon := strings.IndexByte(part, ':')
		if colon <= 0 || colon == len(part)-1 {
			return nil, fmt.Errorf("MCP_SIGNING_KEYS pair %d: missing kid:key separator", i)
		}
		kid := strings.TrimSpace(part[:colon])
		if kid == "" {
			return nil, fmt.Errorf("MCP_SIGNING_KEYS pair %d: kid is empty", i)
		}
		if seen[kid] {
			return nil, fmt.Errorf("MCP_SIGNING_KEYS pair %d: duplicate kid %q", i, kid)
		}
		seen[kid] = true
		// Accept both standard and URL-safe base64 so operators can
		// paste whichever their secret manager gives them.
		key, err := base64.StdEncoding.DecodeString(strings.TrimSpace(part[colon+1:]))
		if err != nil {
			key, err = base64.URLEncoding.DecodeString(strings.TrimSpace(part[colon+1:]))
			if err != nil {
				return nil, fmt.Errorf("MCP_SIGNING_KEYS pair %d: base64 decode failed for kid %q: %w", i, kid, err)
			}
		}
		if len(key) < 32 {
			return nil, fmt.Errorf("MCP_SIGNING_KEYS pair %d: kid %q key is %d bytes; need at least 32 for HMAC-SHA256", i, kid, len(key))
		}
		keys = append(keys, SigningKey{KeyID: kid, Key: key})
	}
	if len(keys) == 0 {
		return nil, errors.New("MCP_SIGNING_KEYS parsed empty (no valid kid:key pairs)")
	}
	return keys, nil
}

// Issuer mints tokens signed with the active key. The active key is the
// first SigningKey in the slice (per ParseSigningKeys ordering).
type Issuer struct {
	keys  []SigningKey
	clock func() time.Time
}

// NewIssuer returns an Issuer using the supplied keys. The first key
// must be present — callers should call ParseSigningKeys first.
func NewIssuer(keys []SigningKey) (*Issuer, error) {
	if len(keys) == 0 {
		return nil, errors.New("at least one signing key is required")
	}
	return &Issuer{keys: keys, clock: time.Now}, nil
}

// Issue mints a signed token with the supplied claims. iat/exp/jti are
// generated by the issuer (callers supply ttl, sub, tenant_id, scopes).
// Scopes are deduplicated and trimmed; empty scopes are rejected because
// a zero-scope token is useless and almost always a bug.
func (iss *Issuer) Issue(sub, tenantID string, scopes []string, ttl time.Duration) (string, Claims, error) {
	if iss == nil || len(iss.keys) == 0 {
		return "", Claims{}, errors.New("issuer has no keys")
	}
	if strings.TrimSpace(sub) == "" {
		return "", Claims{}, errors.New("subject is required")
	}
	if strings.TrimSpace(tenantID) == "" {
		return "", Claims{}, errors.New("tenant_id is required")
	}
	if ttl <= 0 || ttl > 24*time.Hour {
		return "", Claims{}, fmt.Errorf("ttl must be between 1s and 24h, got %s", ttl)
	}
	dedup := map[string]bool{}
	cleaned := make([]string, 0, len(scopes))
	for _, s := range scopes {
		s = strings.TrimSpace(s)
		if s == "" || dedup[s] {
			continue
		}
		dedup[s] = true
		cleaned = append(cleaned, s)
	}
	if len(cleaned) == 0 {
		return "", Claims{}, errors.New("at least one scope is required")
	}
	now := iss.clock().UTC()
	jti := ulid.Make().String()
	claims := Claims{
		Issuer:    tokenIssuer,
		Audience:  tokenAudMCP,
		Subject:   sub,
		TenantID:  tenantID,
		Scopes:    cleaned,
		IssuedAt:  now.Unix(),
		ExpiresAt: now.Add(ttl).Unix(),
		JTI:       jti,
	}
	active := iss.keys[0]
	signed, err := signToken(claims, active)
	if err != nil {
		return "", Claims{}, err
	}
	return signed, claims, nil
}

// ReplayTracker is the surface a verifier uses to reject reused JTIs.
// Implementations are expected to be safe for concurrent use.
type ReplayTracker interface {
	// SeenOrRemember returns true if the JTI was already recorded (a
	// replay). Otherwise it records the JTI with the supplied
	// expiration and returns false.
	SeenOrRemember(jti string, expiresAt time.Time) bool
}

// Verifier validates tokens against the registered keys + replay tracker.
// The clock function is injectable for tests.
type Verifier struct {
	keysByKID map[string]SigningKey
	tracker   ReplayTracker
	clock     func() time.Time
}

// NewVerifier returns a Verifier configured with the supplied keys and
// replay tracker. A nil tracker disables replay checking — only
// appropriate for tests; production callers should always supply one.
func NewVerifier(keys []SigningKey, tracker ReplayTracker) (*Verifier, error) {
	if len(keys) == 0 {
		return nil, errors.New("at least one verification key is required")
	}
	m := make(map[string]SigningKey, len(keys))
	for _, k := range keys {
		m[k.KeyID] = k
	}
	return &Verifier{keysByKID: m, tracker: tracker, clock: time.Now}, nil
}

// ErrMalformedToken is returned when the wire format cannot be parsed.
var ErrMalformedToken = errors.New("mcp: malformed token")

// ErrBadSignature is returned when the signature does not verify under
// the kid claimed in the header (including unknown kid).
var ErrBadSignature = errors.New("mcp: bad signature")

// ErrTokenExpired is returned when exp is in the past beyond skew.
var ErrTokenExpired = errors.New("mcp: token expired")

// ErrTokenNotYetValid is returned when iat is too far in the future.
var ErrTokenNotYetValid = errors.New("mcp: token not yet valid")

// ErrWrongAudience is returned when aud != "mcp".
var ErrWrongAudience = errors.New("mcp: wrong audience")

// ErrWrongIssuer is returned when iss != "auto-bot".
var ErrWrongIssuer = errors.New("mcp: wrong issuer")

// ErrReplayedJTI is returned when the JTI has already been seen.
var ErrReplayedJTI = errors.New("mcp: token replayed")

// Verify parses and validates a token, returning the claims on success.
// It pins alg=HS256, rejects unknown alg/kid, enforces iss/aud/exp/iat,
// and records the JTI to defend against replay.
func (v *Verifier) Verify(token string) (Claims, error) {
	if v == nil {
		return Claims{}, errors.New("verifier is nil")
	}
	parts := strings.Split(token, ".")
	if len(parts) != 3 {
		return Claims{}, ErrMalformedToken
	}
	headerBytes, err := base64.RawURLEncoding.DecodeString(parts[0])
	if err != nil {
		return Claims{}, ErrMalformedToken
	}
	var header struct {
		Alg string `json:"alg"`
		Typ string `json:"typ,omitempty"`
		KID string `json:"kid"`
	}
	if err := json.Unmarshal(headerBytes, &header); err != nil {
		return Claims{}, ErrMalformedToken
	}
	// Pin algorithm. Anything other than HS256 — including the
	// notorious "none" — is rejected without further work.
	if header.Alg != tokenAlg {
		return Claims{}, ErrBadSignature
	}
	key, ok := v.keysByKID[header.KID]
	if !ok {
		return Claims{}, ErrBadSignature
	}
	signingInput := []byte(parts[0] + "." + parts[1])
	gotSig, err := base64.RawURLEncoding.DecodeString(parts[2])
	if err != nil {
		return Claims{}, ErrMalformedToken
	}
	wantSig := hmacSHA256(key.Key, signingInput)
	if subtle.ConstantTimeCompare(gotSig, wantSig) != 1 {
		return Claims{}, ErrBadSignature
	}
	payloadBytes, err := base64.RawURLEncoding.DecodeString(parts[1])
	if err != nil {
		return Claims{}, ErrMalformedToken
	}
	var claims Claims
	if err := json.Unmarshal(payloadBytes, &claims); err != nil {
		return Claims{}, ErrMalformedToken
	}
	if claims.Issuer != tokenIssuer {
		return Claims{}, ErrWrongIssuer
	}
	if claims.Audience != tokenAudMCP {
		return Claims{}, ErrWrongAudience
	}
	now := v.clock().UTC()
	if claims.ExpiresAt > 0 && now.Unix() > claims.ExpiresAt+int64(maxClockSkew/time.Second) {
		return Claims{}, ErrTokenExpired
	}
	if claims.IssuedAt > now.Add(maxClockSkew).Unix() {
		return Claims{}, ErrTokenNotYetValid
	}
	if strings.TrimSpace(claims.JTI) == "" {
		return Claims{}, ErrMalformedToken
	}
	if v.tracker != nil {
		exp := time.Unix(claims.ExpiresAt, 0)
		if v.tracker.SeenOrRemember(claims.JTI, exp) {
			return Claims{}, ErrReplayedJTI
		}
	}
	return claims, nil
}

func signToken(claims Claims, key SigningKey) (string, error) {
	headerJSON, err := json.Marshal(struct {
		Alg string `json:"alg"`
		Typ string `json:"typ"`
		KID string `json:"kid"`
	}{Alg: tokenAlg, Typ: "MCP", KID: key.KeyID})
	if err != nil {
		return "", err
	}
	payloadJSON, err := json.Marshal(claims)
	if err != nil {
		return "", err
	}
	h := base64.RawURLEncoding.EncodeToString(headerJSON)
	p := base64.RawURLEncoding.EncodeToString(payloadJSON)
	sig := hmacSHA256(key.Key, []byte(h+"."+p))
	s := base64.RawURLEncoding.EncodeToString(sig)
	return h + "." + p + "." + s, nil
}

func hmacSHA256(key, msg []byte) []byte {
	mac := hmac.New(sha256.New, key)
	mac.Write(msg)
	return mac.Sum(nil)
}

// GenerateSigningKey returns a fresh random 32-byte key, base64-std
// encoded. Helper for operators bootstrapping MCP_SIGNING_KEYS.
func GenerateSigningKey() (string, error) {
	buf := make([]byte, 32)
	if _, err := rand.Read(buf); err != nil {
		return "", err
	}
	return base64.StdEncoding.EncodeToString(buf), nil
}
