apiVersion: v1
kind: Service
metadata:
  name: {{ include "auto-bot.name" . }}
  labels:
    {{- include "auto-bot.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "auto-bot.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
