#!/usr/bin/env bash
set -euo pipefail

REGION="${AWS_REGION:-us-east-1}"
NAME_PREFIX="${NAME_PREFIX:-auto-bot-dev}"
ENV_FILE="${ENV_FILE:-.env.aws.local}"

random_hex() {
  openssl rand -hex "${1:-24}"
}

upsert_secret() {
  name="$1"
  value="$2"

  if arn=$(aws secretsmanager describe-secret \
    --region "$REGION" \
    --secret-id "$name" \
    --query ARN \
    --output text 2>/dev/null); then
    aws secretsmanager put-secret-value \
      --region "$REGION" \
      --secret-id "$name" \
      --secret-string "$value" >/dev/null
    printf '%s\n' "$arn"
  else
    aws secretsmanager create-secret \
      --region "$REGION" \
      --name "$name" \
      --secret-string "$value" \
      --query ARN \
      --output text
  fi
}

APP_API_TOKEN_VALUE="${APP_API_TOKEN:-$(random_hex 32)}"
LIVEKIT_API_KEY_VALUE="${LIVEKIT_API_KEY:-lk_$(random_hex 8)}"
LIVEKIT_API_SECRET_VALUE="${LIVEKIT_API_SECRET:-$(random_hex 32)}"
LIVEKIT_SIGNAL_PORT="${LIVEKIT_SIGNAL_PORT:-7880}"
LIVEKIT_TCP_PORT="${LIVEKIT_TCP_PORT:-7881}"
LIVEKIT_UDP_PORT="${LIVEKIT_UDP_PORT:-7882}"
FCK_NAT_AMI_ID_VALUE="${FCK_NAT_AMI_ID:-}"
LIVEKIT_DEPLOYMENT_MODE_VALUE="${LIVEKIT_DEPLOYMENT_MODE:-self-hosted}"
LIVEKIT_CLOUD_URL_VALUE="${LIVEKIT_CLOUD_URL:-}"
LIVEKIT_DOMAIN_NAME_VALUE="${LIVEKIT_DOMAIN_NAME:-}"
LIVEKIT_TURN_DOMAIN_NAME_VALUE="${LIVEKIT_TURN_DOMAIN_NAME:-}"
HOSTED_ZONE_ID_VALUE="${HOSTED_ZONE_ID:-}"
APP_DOMAIN_NAME_VALUE="${APP_DOMAIN_NAME:-}"
APP_CERTIFICATE_ARN_VALUE="${APP_CERTIFICATE_ARN:-}"
LIVEKIT_CERTIFICATE_ARN_VALUE="${LIVEKIT_CERTIFICATE_ARN:-}"
LIVEKIT_TURN_CERTIFICATE_ARN_VALUE="${LIVEKIT_TURN_CERTIFICATE_ARN:-}"
LIVEKIT_KEYS_VALUE="${LIVEKIT_API_KEY_VALUE}: ${LIVEKIT_API_SECRET_VALUE}"

APP_API_TOKEN_SECRET_ARN="$(upsert_secret "${NAME_PREFIX}/app-api-token" "$APP_API_TOKEN_VALUE")"
LIVEKIT_API_KEY_SECRET_ARN="$(upsert_secret "${NAME_PREFIX}/livekit-api-key" "$LIVEKIT_API_KEY_VALUE")"
LIVEKIT_API_SECRET_SECRET_ARN="$(upsert_secret "${NAME_PREFIX}/livekit-api-secret" "$LIVEKIT_API_SECRET_VALUE")"
LIVEKIT_KEYS_SECRET_ARN="$(upsert_secret "${NAME_PREFIX}/livekit-keys" "$LIVEKIT_KEYS_VALUE")"

LIVEKIT_CONFIG_VALUE="${LIVEKIT_CONFIG:-}"
if [ "${LIVEKIT_CONFIG_FILE:-}" != "" ]; then
  LIVEKIT_CONFIG_VALUE="$(cat "$LIVEKIT_CONFIG_FILE")"
fi

LIVEKIT_CONFIG_SECRET_ARN=""
if [ "$LIVEKIT_CONFIG_VALUE" != "" ]; then
  LIVEKIT_CONFIG_SECRET_ARN="$(upsert_secret "${NAME_PREFIX}/livekit-config" "$LIVEKIT_CONFIG_VALUE")"
fi

OPENAI_API_KEY_SECRET_ARN=""
if [ "${OPENAI_API_KEY:-}" != "" ]; then
  OPENAI_API_KEY_SECRET_ARN="$(upsert_secret "${NAME_PREFIX}/openai-api-key" "$OPENAI_API_KEY")"
fi

JIRA_API_TOKEN_SECRET_ARN=""
if [ "${JIRA_API_TOKEN:-}" != "" ]; then
  JIRA_API_TOKEN_SECRET_ARN="$(upsert_secret "${NAME_PREFIX}/jira-api-token" "$JIRA_API_TOKEN")"
fi

JIRA_CONFIG_JSON_VALUE="${JIRA_CONFIG_JSON:-}"
if [ "${JIRA_CONFIG_JSON_FILE:-}" != "" ]; then
  JIRA_CONFIG_JSON_VALUE="$(cat "$JIRA_CONFIG_JSON_FILE")"
fi

JIRA_CONFIG_JSON_SECRET_ARN=""
if [ "$JIRA_CONFIG_JSON_VALUE" != "" ]; then
  JIRA_CONFIG_JSON_SECRET_ARN="$(upsert_secret "${NAME_PREFIX}/jira-config-json" "$JIRA_CONFIG_JSON_VALUE")"
fi

JIRA_WEBHOOK_SECRET_SECRET_ARN=""
if [ "${JIRA_WEBHOOK_SECRET:-}" != "" ]; then
  JIRA_WEBHOOK_SECRET_SECRET_ARN="$(upsert_secret "${NAME_PREFIX}/jira-webhook-secret" "$JIRA_WEBHOOK_SECRET")"
fi

GITHUB_APP_ID_SECRET_ARN=""
if [ "${GITHUB_APP_ID:-}" != "" ]; then
  GITHUB_APP_ID_SECRET_ARN="$(upsert_secret "${NAME_PREFIX}/github-app-id" "$GITHUB_APP_ID")"
fi

GITHUB_APP_INSTALLATION_ID_SECRET_ARN=""
if [ "${GITHUB_APP_INSTALLATION_ID:-}" != "" ]; then
  GITHUB_APP_INSTALLATION_ID_SECRET_ARN="$(upsert_secret "${NAME_PREFIX}/github-app-installation-id" "$GITHUB_APP_INSTALLATION_ID")"
fi

GITHUB_APP_PRIVATE_KEY_SECRET_ARN=""
if [ "${GITHUB_APP_PRIVATE_KEY:-}" != "" ]; then
  GITHUB_APP_PRIVATE_KEY_SECRET_ARN="$(upsert_secret "${NAME_PREFIX}/github-app-private-key" "$GITHUB_APP_PRIVATE_KEY")"
fi

cat > "$ENV_FILE" <<EOF
export AWS_REGION='$REGION'
export APP_API_TOKEN_SECRET_ARN='$APP_API_TOKEN_SECRET_ARN'
export LIVEKIT_API_KEY_SECRET_ARN='$LIVEKIT_API_KEY_SECRET_ARN'
export LIVEKIT_API_SECRET_SECRET_ARN='$LIVEKIT_API_SECRET_SECRET_ARN'
export LIVEKIT_KEYS_SECRET_ARN='$LIVEKIT_KEYS_SECRET_ARN'
export LIVEKIT_CONFIG_SECRET_ARN='$LIVEKIT_CONFIG_SECRET_ARN'
export OPENAI_API_KEY_SECRET_ARN='$OPENAI_API_KEY_SECRET_ARN'
export JIRA_API_TOKEN_SECRET_ARN='$JIRA_API_TOKEN_SECRET_ARN'
export JIRA_CONFIG_JSON_SECRET_ARN='$JIRA_CONFIG_JSON_SECRET_ARN'
export JIRA_WEBHOOK_SECRET_SECRET_ARN='$JIRA_WEBHOOK_SECRET_SECRET_ARN'
export GITHUB_APP_ID_SECRET_ARN='$GITHUB_APP_ID_SECRET_ARN'
export GITHUB_APP_INSTALLATION_ID_SECRET_ARN='$GITHUB_APP_INSTALLATION_ID_SECRET_ARN'
export GITHUB_APP_PRIVATE_KEY_SECRET_ARN='$GITHUB_APP_PRIVATE_KEY_SECRET_ARN'
export GITHUB_DEFAULT_REPO='${GITHUB_DEFAULT_REPO:-}'
export GITHUB_ALLOWED_REPOS='${GITHUB_ALLOWED_REPOS:-}'
export GITHUB_PR_COMMENTS_ENABLED='${GITHUB_PR_COMMENTS_ENABLED:-false}'
export AGENT_PM_MODEL='${AGENT_PM_MODEL:-us.anthropic.claude-haiku-4-5-20251001-v1:0}'
export AGENT_REVIEW_MODEL='${AGENT_REVIEW_MODEL:-us.anthropic.claude-sonnet-4-6}'
export FCK_NAT_AMI_ID='$FCK_NAT_AMI_ID_VALUE'
export LIVEKIT_DEPLOYMENT_MODE='$LIVEKIT_DEPLOYMENT_MODE_VALUE'
export LIVEKIT_CLOUD_URL='$LIVEKIT_CLOUD_URL_VALUE'
export LIVEKIT_DOMAIN_NAME='$LIVEKIT_DOMAIN_NAME_VALUE'
export LIVEKIT_TURN_DOMAIN_NAME='$LIVEKIT_TURN_DOMAIN_NAME_VALUE'
export HOSTED_ZONE_ID='$HOSTED_ZONE_ID_VALUE'
export APP_DOMAIN_NAME='$APP_DOMAIN_NAME_VALUE'
export APP_CERTIFICATE_ARN='$APP_CERTIFICATE_ARN_VALUE'
export LIVEKIT_CERTIFICATE_ARN='$LIVEKIT_CERTIFICATE_ARN_VALUE'
export LIVEKIT_TURN_CERTIFICATE_ARN='$LIVEKIT_TURN_CERTIFICATE_ARN_VALUE'
EOF

printf 'Wrote Terraform/Terragrunt secret environment exports to %s\n' "$ENV_FILE"
printf 'Source it before running Terragrunt:\n'
printf '  set -a; source %s; set +a\n' "$ENV_FILE"
